### ISSUE TITLE
Build issue - sincos

### ISSUE THREAD

**Issue by chrispike-bbc** [choene/libmysofa#3]
sincos seems not to be available in C99 on OS X:
> /Users/chrisp/Documents/code/libmysofa/src/tools.c:65:3: warning: implicit declaration of function 'sincos' is invalid in C99
>       [-Wimplicit-function-declaration]
>                 sincos(theta, &z, &x);

https://software.intel.com/en-us/forums/intel-c-compiler/topic/531738
I'm running Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

**Comment by choene** [comment]
fixed in master
